# Generated by Django 2.2.6 on 2019-11-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191110_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_work',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
