# Generated by Django 2.2.6 on 2019-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191113_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leadership',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leadership',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subleader',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subleader',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subleader',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
